// Writes src/fonts.generated.ts from fonts/*.woff, so the templates' fonts travel inside the code: every bundle
// and runtime gets them with no file access. Run after replacing a font: pnpm --filter @aiontheballot/og fonts
import { readFile, writeFile } from 'node:fs/promises';

const FONTS = [
  ['SAIRA_CONDENSED_700', 'saira-condensed-latin-700-normal.woff'],
  ['ROBOTO_SLAB_400', 'roboto-slab-latin-400-normal.woff'],
];

const lines = [
  '// Generated by scripts/embed-fonts.mjs from fonts/: do not edit. Base64 WOFF files.',
  '',
];
for (const [name, file] of FONTS) {
  const data = await readFile(new URL(`../fonts/${file}`, import.meta.url));
  lines.push(`/** fonts/${file} */`, `export const ${name} = '${data.toString('base64')}';`, '');
}
await writeFile(new URL('../src/fonts.generated.ts', import.meta.url), lines.join('\n'));
