#!/usr/bin/env bash
# Generates the aiontheballot database passwords and seals every aiontheballot secret for the danilupion.com cluster
# into a gitops checkout (ADR-0001). Nothing secret is printed or written unencrypted: passwords live in shell
# variables and reach kubectl through /dev/fd (process substitution), never through argv or a file.
#
# Usage: scripts/seal-gitops-secrets.sh <path-to-gitops>
# Asks for the Harbor secret of robot$aiontheballot-pull (input hidden). Refuses to overwrite: to rotate, delete the
# files first. The four passwords are always regenerated together, and the postgresql provisioning hook re-applies them
# to the roles on its next sync.
set -euo pipefail

GITOPS="${1:?usage: $0 <path-to-gitops>}"
HARBOR_ROBOT="${HARBOR_ROBOT:-robot\$aiontheballot-pull}"
# Overridable for a dry run against a throwaway certificate (KUBESEAL_ARGS="--cert cert.pem").
read -r -a KUBESEAL_ARGS <<<"${KUBESEAL_ARGS:---context danilupion.com --controller-namespace sealed-secrets --controller-name sealed-secrets}"

PG_DIR="$GITOPS/clusters/danilupion-com/resources/data/postgresql"
APP_DIR="$GITOPS/clusters/danilupion-com/resources/apps/aiontheballot/secrets"
DB_HOST="postgresql.postgresql.svc.cluster.local:5432"

files=("$PG_DIR/aiontheballot-db-credentials.yaml" "$APP_DIR/aiontheballot-harbor-pull.yaml"
  "$APP_DIR/aiontheballot-owner-db.yaml" "$APP_DIR/aiontheballot-web-db.yaml" "$APP_DIR/aiontheballot-admin-db.yaml"
  "$APP_DIR/aiontheballot-worker-db.yaml")
for f in "${files[@]}"; do
  if [ -e "$f" ]; then
    echo "Refusing to overwrite $f" >&2
    exit 1
  fi
done
[ -d "$PG_DIR" ] || { echo "Not a gitops checkout: $PG_DIR is missing" >&2; exit 1; }
mkdir -p "$APP_DIR"

# seal <out> <header> <wave|-> <kubectl create secret args...>
# Writes header comments plus the SealedSecret. Secrets in the app namespace get sync wave -2, so Argo CD creates them
# before the migration Job (wave -1) and the Deployments (wave 0).
seal() {
  local out="$1" header="$2" wave="$3"
  shift 3
  local tmp="$out.tmp"
  if ! {
    printf '# yamllint disable rule:line-length\n'
    printf '# SealedSecret encryptedData contains long base64 strings that cannot be wrapped.\n'
    printf '%s\n' "$header"
    kubectl create secret "$@" --dry-run=client -o yaml \
      | kubeseal "${KUBESEAL_ARGS[@]}" --format yaml \
      | if [ "$wave" = - ]; then sed '/^---$/d'; else
          kubectl annotate --local -f - "argocd.argoproj.io/sync-wave=$wave" -o yaml
        fi
  } >"$tmp"; then
    rm -f "$tmp"
    echo "Failed to seal $out" >&2
    exit 1
  fi
  mv "$tmp" "$out"
  echo "sealed $out"
}

printf 'Harbor secret for %s: ' "$HARBOR_ROBOT"
IFS= read -rs HARBOR_SECRET
echo
[ -n "$HARBOR_SECRET" ] || { echo "Empty Harbor secret" >&2; exit 1; }

owner_pw="$(openssl rand -hex 32)"
web_pw="$(openssl rand -hex 32)"
admin_pw="$(openssl rand -hex 32)"
worker_pw="$(openssl rand -hex 32)"
url() { printf 'postgres://%s:%s@%s/aiontheballot?sslmode=disable' "$1" "$2" "$DB_HOST"; }

seal "$PG_DIR/aiontheballot-db-credentials.yaml" \
  "# Read by the postgresql provisioning hook: owner and extra-role passwords for the aiontheballot database
# (openssl rand -hex 32 each). Each must match DATABASE_URL in aiontheballot/aiontheballot-<role>-db.
# Generated by scripts/seal-gitops-secrets.sh in pauseai-en-espanol/aiontheballot." - \
  generic aiontheballot-db-credentials -n postgresql \
  --from-file=AIONTHEBALLOT_OWNER_PASSWORD=<(printf %s "$owner_pw") \
  --from-file=AIONTHEBALLOT_WEB_PASSWORD=<(printf %s "$web_pw") \
  --from-file=AIONTHEBALLOT_ADMIN_PASSWORD=<(printf %s "$admin_pw") \
  --from-file=AIONTHEBALLOT_WORKER_PASSWORD=<(printf %s "$worker_pw")

seal "$APP_DIR/aiontheballot-harbor-pull.yaml" \
  "# Pull secret for harbor.danilupion.com/aiontheballot ($HARBOR_ROBOT, pull only), on the default SA." -2 \
  generic aiontheballot-harbor-pull -n aiontheballot --type=kubernetes.io/dockerconfigjson \
  --from-file=.dockerconfigjson=<(HARBOR_ROBOT="$HARBOR_ROBOT" HARBOR_SECRET="$HARBOR_SECRET" jq -cn '
    {auths: {"harbor.danilupion.com": {username: env.HARBOR_ROBOT, password: env.HARBOR_SECRET,
      auth: ("\(env.HARBOR_ROBOT):\(env.HARBOR_SECRET)" | @base64)}}}')

seal "$APP_DIR/aiontheballot-owner-db.yaml" \
  "# DATABASE_URL for aiontheballot_owner (migrations only): $(url aiontheballot_owner '<OWNER_PASSWORD>')" -2 \
  generic aiontheballot-owner-db -n aiontheballot --from-file=DATABASE_URL=<(url aiontheballot_owner "$owner_pw")

# The runtime URLs are sealed now so each password is generated once; the API and worker use them from M1.
seal "$APP_DIR/aiontheballot-web-db.yaml" \
  "# DATABASE_URL for aiontheballot_web (API public routes, read-only): $(url aiontheballot_web '<WEB_PASSWORD>')" -2 \
  generic aiontheballot-web-db -n aiontheballot --from-file=DATABASE_URL=<(url aiontheballot_web "$web_pw")

seal "$APP_DIR/aiontheballot-admin-db.yaml" \
  "# DATABASE_URL for aiontheballot_admin (API admin routes): $(url aiontheballot_admin '<ADMIN_PASSWORD>')" -2 \
  generic aiontheballot-admin-db -n aiontheballot --from-file=DATABASE_URL=<(url aiontheballot_admin "$admin_pw")

seal "$APP_DIR/aiontheballot-worker-db.yaml" \
  "# DATABASE_URL for aiontheballot_worker (background worker): $(url aiontheballot_worker '<WORKER_PASSWORD>')" -2 \
  generic aiontheballot-worker-db -n aiontheballot --from-file=DATABASE_URL=<(url aiontheballot_worker "$worker_pw")

unset HARBOR_SECRET owner_pw web_pw admin_pw worker_pw
echo "Done. Review with: git -C \"$GITOPS\" status"
