#!/usr/bin/env bash
# Seals the GlitchTip DSN of each aiontheballot app (web, admin, api) for the danilupion.com cluster into a gitops
# checkout (ADR-0003 §7). Nothing secret is printed or written unencrypted: each DSN is read with hidden input and
# reaches kubectl through /dev/fd (process substitution), never through argv or a file.
#
# Usage: scripts/seal-glitchtip-dsns.sh <path-to-gitops>
# Paste each project's DSN from GlitchTip (project settings, Client Keys). The host is rewritten to the in-cluster
# Service, because GlitchTip's UI host is VPN-only and the apps post in-cluster. Refuses to overwrite: to rotate,
# delete the files first.
set -euo pipefail

GITOPS="${1:?usage: $0 <path-to-gitops>}"
# Overridable for a dry run against a throwaway certificate (KUBESEAL_ARGS="--cert cert.pem").
read -r -a KUBESEAL_ARGS <<<"${KUBESEAL_ARGS:---context danilupion.com --controller-namespace sealed-secrets --controller-name sealed-secrets}"

APP_DIR="$GITOPS/clusters/danilupion-com/resources/apps/aiontheballot/secrets"
SERVICE_HOST="glitchtip-web.glitchtip.svc.cluster.local"
APPS=(web admin api)

[ -d "$APP_DIR" ] || { echo "Not a gitops checkout with aiontheballot secrets: $APP_DIR is missing" >&2; exit 1; }
for app in "${APPS[@]}"; do
  if [ -e "$APP_DIR/aiontheballot-$app-glitchtip.yaml" ]; then
    echo "Refusing to overwrite $APP_DIR/aiontheballot-$app-glitchtip.yaml" >&2
    exit 1
  fi
done

for app in "${APPS[@]}"; do
  printf 'GlitchTip DSN of project aiontheballot-%s: ' "$app"
  IFS= read -rs dsn
  echo
  # https://<key>@<any host>/<project> becomes http://<key>@<in-cluster Service>/<project>.
  if [[ ! "$dsn" =~ ^https?://([0-9A-Fa-f-]+)@[^/@]+/([0-9]+)/?$ ]]; then
    echo "That is not a GlitchTip DSN (expected https://<key>@<host>/<project>); nothing written for $app" >&2
    exit 1
  fi
  internal="http://${BASH_REMATCH[1]}@$SERVICE_HOST/${BASH_REMATCH[2]}"
  out="$APP_DIR/aiontheballot-$app-glitchtip.yaml"
  tmp="$out.tmp"
  # Sync wave -2, like the other aiontheballot secrets: created before the Deployments (wave 0).
  if ! {
    printf '# yamllint disable rule:line-length\n'
    printf '# SealedSecret encryptedData contains long base64 strings that cannot be wrapped.\n'
    printf '# SENTRY_DSN for aiontheballot-%s: GlitchTip project aiontheballot-%s, through the in-cluster Service.\n' \
      "$app" "$app"
    printf '# Generated by scripts/seal-glitchtip-dsns.sh in pauseai-en-espanol/aiontheballot.\n'
    kubectl create secret generic "aiontheballot-$app-glitchtip" -n aiontheballot \
      --from-file=SENTRY_DSN=<(printf %s "$internal") --dry-run=client -o yaml \
      | kubeseal "${KUBESEAL_ARGS[@]}" --format yaml \
      | kubectl annotate --local -f - "argocd.argoproj.io/sync-wave=-2" -o yaml
  } >"$tmp"; then
    rm -f "$tmp"
    echo "Failed to seal $out" >&2
    exit 1
  fi
  mv "$tmp" "$out"
  echo "sealed $out"
done
unset dsn internal
